[package]
name = "font"
version = "0.1.0"
authors = ["Sebastian Köln <sebk@rynx.org>"]
edition = "2018"

[features]
unstable = ["slotmap/unstable", "tuple/nightly"]
tools = ["env_logger"]

[dependencies]
encoding = { git = "https://github.com/pdf-rs/encoding/" }
pathfinder_geometry = { git = "https://github.com/s3bk/pathfinder/" }
pathfinder_content = { git = "https://github.com/s3bk/pathfinder/" }
vector = { git = "https://github.com/s3bk/vector/" }
tuple = { git = "https://github.com/s3bk/tuple/" }
nom = "5.0.0"
log = "0.4.8"
rand = { version = "0.7.0", features = ["wasm-bindgen"] }
slotmap = { version = "0.4.0" }
decorum = "0.1.3"
itertools = "0.8.0"
indexmap = "1.0"
brotli-decompressor = "2.3.0"
inflate = "0.4.5"
raqote = { version = "*", default-features = false }
walkdir = "2.2.9"
env_logger = { version = "*", optional=true }

[[bin]]
name = "font2svg"
required-features = ["tools"]

[[bin]]
name = "glyph2svg"
required-features = ["tools"]

[[bin]]
name = "parse_fonts"
required-features = ["tools"]

[[bin]]
name = "render_text"
required-features = ["tools"]
