[package]
name = "font"
version = "0.1.0"
authors = ["Sebastian Köln <sebk@rynx.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding = { git = "https://github.com/pdf-rs/encoding/" }
pathfinder_geometry = { git = "https://github.com/s3bk/pathfinder/" }
pathfinder_content = { git = "https://github.com/s3bk/pathfinder/" }
vector = { git = "https://github.com/s3bk/vector/" }
tuple = { git = "https://gitlab.com/sebk/tuple/", features=["nightly"] }
nom = "5.0.0"
log = "0.4.8"
env_logger = "0.6.2"
rand = { version = "0.7.0", features = ["wasm-bindgen"] }
slotmap = { version = "0.3.0", features = ["unstable"] }
decorum = "0.1.3"
itertools = "0.8.0"
indexmap = "1.0"
brotli = "3.3.0"
inflate = "0.4.5"
raqote = { version = "*", default-features = false }

walkdir = "2.2.9"
#jemallocator = "0.3.0"
